language: node_js
 - "8.7"

addons:
  ssh_known_hosts: alfa.smartstorm.io

before_install:
 - openssl aes-256-cbc -K $encrypted_8f2e1fe0e7f3_key -iv $encrypted_8f2e1fe0e7f3_iv -in deploy_rsa.enc -out deploy_rsa -d
 - eval "$(ssh-agent -s)"
 - chmod 600 /tmp/deploy_rsa
 - ssh-add /tmp/deploy_rsa

before_script:
 - npm install
 - npm install -g @angular/cli
 
script:
  - ng build
