language: node_js
 - "8.7"

before_install:
 - openssl aes-256-cbc -K $encrypted_8f2e1fe0e7f3_key -iv $encrypted_8f2e1fe0e7f3_iv -in deploy_rsa.enc -out deploy_rsa -d

before_script:
 - npm install
 - npm install -g @angular/cli
 
script:
  - ng build
